[
  {
    "id": 13,
    "title": "Roland Garros 2026: Cobolli in finale, primo italiano da Panatta. Oggi sfida con Zverev",
    "deck": "Flavio Cobolli gioca oggi la sua prima finale in uno Slam contro Alexander Zverev. Ieri Mirra Andreeva ha vinto il titolo femminile. Errani e Vavassori campioni nel doppio misto per il quarto major insieme.",
    "category": "europa",
    "date": "7 giugno 2026",
    "readTime": 3,
    "featured": true,
    "image": "https://images.pexels.com/photos/1461974/pexels-photo-1461974.jpeg?auto=compress&cs=tinysrgb&w=1260&q=80",
    "body": "<p>Parigi, Philippe Chatrier. Oggi pomeriggio Flavio Cobolli scende in campo per la finale del Roland Garros 2026 contro Alexander Zverev. È un momento storico per il tennis italiano: nessun uomo ha raggiunto la finale di uno Slam dal 1976, quando Adriano Panatta vinse proprio qui a Parigi. Cinquant'anni dopo, il 23enne romano ci riprova.</p><h2>Un percorso straordinario</h2><p>Cobolli, testa di serie numero 10, ha costruito questa finale match dopo match su una terra rossa che non è storicamente la sua superficie preferita. In semifinale non ha dovuto giocare: il connazionale Matteo Arnaldi si è ritirato per un virus intestinale, un epilogo amaro per l'italiano di Sanremo che aveva sognato una finale tutta azzurra. Ma la storia che conta oggi è quella di Cobolli: un giocatore entrato nella top 10 del ranking ATP per la prima volta in carriera, che si ritrova a un set dal primo titolo Slam.</p><blockquote>\"Non ho ancora realizzato dove sono. Ci penserò dopo, adesso devo restare concentrato sul gioco.\" — Flavio Cobolli, conferenza stampa di sabato</blockquote><p>Dall'altra parte della rete c'è Zverev, numero 2 del mondo, alla sua quarta finale in uno Slam. Il tedesco è in cerca del primo titolo Major dopo tre finali perse: Australian Open 2020, US Open 2021 e Roland Garros 2022. Ha già battuto Cobolli tre volte su quattro nei precedenti, ma la testa di serie numero 10 ha dimostrato in questo torneo di essere capace di battere chiunque.</p><h2>Il contorno azzurro</h2><p>In attesa della finale maschile, il bilancio italiano di questo Roland Garros è già straordinario. Ieri, sabato 6 giugno, Sara Errani e Andrea Vavassori hanno vinto per la seconda volta consecutiva il titolo di doppio misto, battendo in rimonta la coppia Dabrowski-King (4-6, 6-3, 10-4). È il quarto titolo Slam insieme per la coppia italiana: Errani diventa così l'italiana più vincente nella storia del Roland Garros, con quattro titoli all'attivo, al pari di Nicola Pietrangeli.</p><h2>Il titolo femminile ad Andreeva</h2><p>La finale femminile di ieri ha incoronato Mirra Andreeva, 17 anni, come nuova campionessa parigina. La tennista russa ha battuto la polacca Maja Chwalinska in due set, conquistando il primo titolo Slam in carriera. Un risultato che conferma come il tennis femminile stia attraversando una fase di profondo rinnovamento generazionale. Oggi tocca agli uomini scrivere la storia — e l'Italia ha un candidato.</p>"
  },
  {
    "id": 14,
    "title": "Caso Garlasco: Sempio verso il processo, Stasi chiede la revisione. Diciannove anni dopo",
    "deck": "La Procura di Pavia ha concluso le indagini indicando Andrea Sempio come unico responsabile della morte di Chiara Poggi. Stasi, condannato definitivamente nel 2015, valuta la richiesta di revisione. Il Guardasigilli Nordio: 'Una vicenda paradossale'.",
    "category": "europa",
    "date": "7 giugno 2026",
    "readTime": 5,
    "featured": false,
    "image": "https://images.pexels.com/photos/20413635/pexels-photo-20413635.jpeg?auto=compress&cs=tinysrgb&w=1260&q=80",
    "body": "<p>Diciannove anni dopo il delitto di Garlasco, il caso è arrivato a un punto di svolta che nessuno avrebbe previsto quando Alberto Stasi fu condannato in via definitiva nel 2015. Il 7 maggio 2026, la Procura di Pavia ha depositato le conclusioni della nuova inchiesta: Andrea Sempio, amico del fratello della vittima, è indicato come unico responsabile dell'omicidio di Chiara Poggi, uccisa il 13 agosto 2007 nella villetta di famiglia in via Pascoli a Garlasco. Stasi, che sconta ancora la sua pena di 16 anni, è in attesa di capire se potrà chiedere la revisione del processo.</p><h2>Chi è Andrea Sempio</h2><p>Sempio era stato iscritto nel registro degli indagati nel marzo 2025, con l'accusa iniziale di concorso in omicidio. In meno di un anno, l'ipotesi accusatoria si è trasformata radicalmente: secondo la Procura, Sempio sarebbe l'unico responsabile, il che implica — almeno logicamente — che Stasi non avrebbe commesso il delitto per cui è stato condannato. Il 28 maggio 2026, la Procura di Pavia ha disposto anche una consulenza psichiatrica sull'indagato, un passaggio che potrebbe precludere o ritardare il rinvio a giudizio.</p><blockquote>\"Il quadro per noi è grave. La sentenza di condanna di Stasi viene disintegrata dalla Procura da tutti i punti di vista.\" — avvocato Bocellari, difensore di Stasi, maggio 2026</blockquote><p>La difesa di Stasi ha già annunciato di stare valutando la richiesta di revisione del processo. Ma la strada è più complicata di quanto sembri. Come ha spiegato un docente di Diritto Processuale Penale Comparato su Il Fatto Quotidiano, una memoria investigativa di 105 pagine non equivale a una prova nuova nel senso tecnico richiesto per demolire un giudicato. Il processo a Sempio e la revisione del processo a Stasi sono due procedimenti separati che possono coesistere senza necessariamente condizionarsi.</p><h2>Un caso che non trova pace</h2><p>Il caso si è ulteriormente ingarbugliato nelle ultime settimane. L'avvocato di Stasi, Antonio De Rensis, è stato iscritto nel registro degli indagati per diffamazione, su denuncia di Stefania Cappa, cugina di Chiara Poggi, dopo una serie di dichiarazioni televisive. Sono stati indagati anche un ex maresciallo dei carabinieri e un inviato de Le Iene. Parallelamente, nuove intercettazioni dei genitori di Sempio — risalenti a poco dopo la condanna di Stasi — mostrano perplessità sulla colpevolezza del condannato.</p><h2>La politica entra nel caso</h2><p>Il Guardasigilli Carlo Nordio ha definito pubblicamente la vicenda \"paradossale\", riferendosi alla dinamica che ha portato alla condanna di Stasi dopo due assoluzioni nei gradi precedenti. Una dichiarazione rara per un ministro in carica su un caso ancora aperto, che ha acceso ulteriori polemiche. Nel mezzo di tutto questo c'è ancora Chiara Poggi, la cui famiglia chiede da diciannove anni soltanto una cosa: la verità.</p>"
  },
  {
    "id": 11,
    "title": "Vertice di Londra senza l'Italia: Macron, Merz e Starmer ridisegnano l'asse europeo sull'Ucraina",
    "deck": "Oggi Macron, Merz e Starmer si sono riuniti a Londra con Zelensky per strutturare una strategia negoziale europea autonoma. Roma assente: pesa il veto categorico di Meloni all'invio di truppe.",
    "category": "europa",
    "date": "7 giugno 2026",
    "readTime": 4,
    "featured": false,
    "image": "https://images.pexels.com/photos/12049132/pexels-photo-12049132.jpeg?auto=compress&cs=tinysrgb&w=1260&q=80",
    "body": "<p>Oggi a Londra si è tenuto un vertice che potrebbe segnare una svolta nella gestione europea del conflitto ucraino. Keir Starmer, Emmanuel Macron e Friedrich Merz si sono riuniti attorno allo stesso tavolo con Volodymyr Zelensky, avviando quello che i tre leader definiscono il formato dei \"volenterosi\": un asse ristretto e decisionista che intende colmare il vuoto lasciato dal disimpegno americano. L'Italia non c'era.</p><h2>Una sedia vuota a Londra</h2><p>L'assenza di Giorgia Meloni non è un disguido di calendario. È la cristallizzazione di una linea politica che Roma ha tenuto ferma dall'inizio del conflitto: nessuna disponibilità all'invio di truppe italiane sul terreno ucraino, nessun coinvolgimento in iniziative che potrebbero essere lette come escalation. Palazzo Chigi ha derubricato l'assenza a un problema logistico legato alla festa dei Carabinieri, ma la spiegazione non ha convinto nessuno tra i partner europei. Il gelo tra Roma, Parigi e Berlino è palpabile.</p><blockquote>\"L'Europa non può più aspettare che Washington decida per noi. Dobbiamo costruire la nostra posizione negoziale adesso, non dopo il vertice di Ankara.\" — Emmanuel Macron, Londra, 7 giugno 2026</blockquote><p>Sul piano operativo, l'assenza italiana non cambia l'agenda immediata: la liturgia di questi vertici non produce svolte sul campo. Ma sul piano del prestigio e dell'influenza, Roma si ritrova ai margini di un processo che potrebbe ridisegnare i termini di un eventuale negoziato con Mosca.</p><h2>Il calendario dei cinque vertici</h2><p>Il vertice di Londra apre una sequenza di cinque appuntamenti chiave: il G7, il Consiglio Europeo, il summit NATO ad Ankara il 7-8 luglio, e la riunione allargata dei volenterosi il 14 luglio a Parigi. La logica è quella di arrivare ad Ankara con una posizione europea già strutturata, che non si limiti al sostegno militare ma proponga una architettura per un futuro negoziato bilaterale in cui l'Europa rivendica un ruolo da protagonista — non da comprimaria degli americani.</p><h2>Il nodo del ruolo europeo</h2><p>Il problema di fondo che questo formato cerca di risolvere è strutturale: l'Europa ha finanziato largamente la guerra ucraina ma ha avuto poca voce in capitolo sulla sua direzione politica. Adesso, con Trump che si sfila progressivamente dai dossier europei, Macron, Merz e Starmer vedono un'opportunità per riempire quel vuoto. Se riusciranno a trasformare questa ambizione in posizioni negoziali credibili è la domanda che Ankara dovrà rispondere.</p>"
  },
  {
    "id": 12,
    "title": "NATO ad Ankara il 7 luglio: il vertice che ridefinisce l'alleanza nell'era Trump",
    "deck": "Tra un mese si aprirà il summit NATO nella capitale turca. Sul tavolo: 70 miliardi per l'Ucraina, truppe americane ridotte, possibili armi nucleari tattiche in Polonia e nei Baltici. Un'alleanza che si trasforma.",
    "category": "europa",
    "date": "7 giugno 2026",
    "readTime": 5,
    "featured": false,
    "image": "https://images.pexels.com/photos/7016972/pexels-photo-7016972.jpeg?auto=compress&cs=tinysrgb&w=1260&q=80",
    "body": "<p>Manca esattamente un mese al vertice NATO di Ankara, fissato per il 7 e 8 luglio 2026. Sarà il 36° summit dell'alleanza e il secondo ospitato dalla Turchia, dopo Istanbul 2004. Ma le circostanze geopolitiche in cui si svolgerà sono radicalmente diverse da qualsiasi precedente: un'America che riduce la propria presenza militare in Europa, una guerra in Ucraina giunta al quinto anno senza soluzioni in vista, e un'Europa che cerca di trovare una voce autonoma in un'alleanza che rischia di essere ridefinita dai fatti prima che dai trattati.</p><h2>Il dossier più urgente: i 70 miliardi per l'Ucraina</h2><p>Secondo fonti citate da Politico, i paesi NATO stanno elaborando un nuovo pacchetto di aiuti finanziari a Kiev da 70 miliardi di euro, da annunciare proprio ad Ankara. Di questi, 40 miliardi sarebbero nuovi stanziamenti e 30 miliardi parte del pacchetto da 90 miliardi già approvato dall'UE. La complicazione non è solo finanziaria: alcuni paesi europei contestano la distribuzione del peso, ritenendo che il contributo sia troppo squilibrato a favore dei paesi dell'Europa orientale più esposti alla minaccia russa.</p><blockquote>\"Da qui ad Ankara la differenza tra dichiarazione politica e atto operativo sarà il criterio decisivo per leggere ogni sviluppo.\" — analisi pubblicata su Sbircia la Notizia Magazine, 22 maggio 2026</blockquote><p>Il pacchetto deve fare i conti anche con l'incognita americana. Washington ha ridotto le proprie brigate da combattimento in Europa da quattro a tre, tagliando circa 5.000 soldati dalla Germania. Il segnale politico è chiaro: l'America vuole che gli europei paghino di più e gestiscano di più. Il problema è che \"di più\" è ancora una formula vaga, senza scadenze o meccanismi di verifica credibili.</p><h2>Il nodo nucleare</h2><p>Il dossier più delicato che potrebbe emergere ad Ankara è quello della deterrenza nucleare. Gli Stati Uniti starebbero valutando lo schieramento di nuove armi nucleari tattiche in Polonia e nei paesi baltici, in risposta alla retorica nucleare di Mosca degli ultimi due anni. Una scelta che, se confermata, segnerebbe una discontinuità profonda con la postura degli ultimi trent'anni e alimenterebbe tensioni già alte con la Russia. Per l'Italia — che ospita armi nucleari NATO ad Aviano e Ghedi — la questione ha implicazioni dirette che Roma non ha ancora affrontato pubblicamente.</p><h2>La Turchia padrona di casa</h2><p>Non è secondario il fatto che il vertice si tenga ad Ankara. Erdoğan ha sempre giocato un ruolo ambiguo nella crisi ucraina — mantenendo relazioni con Mosca pur restando formalmente nel campo NATO — e la scelta di ospitare il summit è un segnale di riabilitazione internazionale ma anche un'opportunità per Ankara di riposizionarsi come mediatore indispensabile. Una presenza ingombrante al centro di un'alleanza che cerca unità.</p>"
  },
  {
    "id": 9,
    "title": "Armenia al voto: Pashinyan in vantaggio, la Russia perde terreno nel Caucaso",
    "deck": "Le urne chiudono questa sera a Erevan dopo una campagna elettorale senza precedenti per tensione geopolitica. I primi dati danno il premier uscente in vantaggio, mentre Mosca incassa un nuovo segnale di distanza.",
    "category": "europa",
    "date": "7 giugno 2026",
    "readTime": 4,
    "featured": false,
    "image": "https://images.pexels.com/photos/17211499/pexels-photo-17211499.jpeg?auto=compress&cs=tinysrgb&w=1260&q=80",
    "body": "<p>Le elezioni parlamentari armene del 7 giugno 2026 si stanno chiudendo con un dato politico che va ben oltre il confine del piccolo paese caucasico. I primi exit poll danno Nikol Pashinyan e il suo partito Contratto Civile in netto vantaggio sulle forze filorusse, in una tornata che molti analisti avevano già definito la più geopoliticamente significativa dalla fine dell'Unione Sovietica.</p><h2>Il voto come scelta di campo</h2><p>Formalmente si trattava di eleggere un nuovo Parlamento. Nella sostanza, gli armeni sono stati chiamati a rispondere a una domanda più profonda: guardare a Ovest o restare nell'orbita di Mosca? Pashinyan ha costruito tutta la campagna attorno a questa dicotomia, capitalizzando sull'onda di legittimità generata dal summit della Comunità Politica Europea ospitato a Erevan a maggio, un evento che ha portato in Armenia Macron, Meloni e Zelensky in un colpo solo.</p><blockquote>\"Non si tratta di scegliere tra Russia e Europa. Si tratta di scegliere tra il passato e il futuro.\" — Nikol Pashinyan, comizio finale della campagna, 6 giugno 2026</blockquote><p>La risposta di Mosca nelle ultime settimane è stata quella di chi sente il terreno spostarsi sotto i piedi: avvertimenti espliciti sull'uscita dall'Unione Economica Eurasiatica, pressioni commerciali, campagne di disinformazione documentate dall'intelligence armena. Una stretta che, secondo molti osservatori, ha finito per rafforzare anziché indebolire la posizione di Pashinyan.</p><h2>Il sostegno occidentale</h2><p>Washington ha fatto una scelta di campo inusualmente esplicita: l'amministrazione americana ha espresso pubblico sostegno a Pashinyan, rompendo con la tradizionale ambiguità che aveva caratterizzato la politica americana verso il Caucaso. L'UE, dal canto suo, ha avanzato la possibilità di aperture concrete sul percorso di associazione — non ancora adesione, ma un segnale tangibile di direzione.</p><h2>Cosa cambia per la regione</h2><p>Se i dati preliminari saranno confermati, la vittoria di Pashinyan segnerà un punto di non ritorno nella traiettoria dell'Armenia. Non necessariamente una rottura immediata con la Russia — le dipendenze energetiche e di sicurezza sono ancora reali — ma un consolidamento dell'orientamento europeo che renderà sempre più difficile per Mosca considerare Erevan un paese affidabile nella propria sfera d'influenza.</p>"
  },
  {
    "id": 10,
    "title": "Ucraina, la guerra dei droni arriva a San Pietroburgo: Zelensky sfida Putin sul suo terreno",
    "deck": "Nella notte tra il 5 e il 6 giugno Kiev ha lanciato 376 droni sulla Russia, colpendo un terminal petrolifero a 1.100 km dal confine. La NATO discute 70 miliardi di aiuti. Putin rifiuta l'incontro con Zelensky.",
    "category": "europa",
    "date": "7 giugno 2026",
    "readTime": 5,
    "featured": false,
    "image": "https://images.pexels.com/photos/17178100/pexels-photo-17178100.jpeg?auto=compress&cs=tinysrgb&w=1260&q=80",
    "body": "<p>La guerra in Ucraina ha raggiunto ieri un'escalation simbolica e strategica di prima grandezza. Nella notte tra il 5 e il 6 giugno, le forze ucraine hanno lanciato un attacco massiccio con circa 376 droni su territorio russo, colpendo un terminal petrolifero a San Pietroburgo — a oltre 1.100 chilometri dal confine ucraino. La scelta del bersaglio non è casuale: il Forum Economico di San Pietroburgo era in corso, con Putin atteso al palco.</p><h2>La dottrina delle \"sanzioni a lungo raggio\"</h2><p>Zelensky ha definito l'operazione con un'espressione deliberatamente provocatoria: \"sanzioni a lungo raggio\". È la risposta ucraina al rifiuto di Putin di sedersi al tavolo dei negoziati — il presidente russo ha dichiarato di non vedere \"per il momento la necessità\" di un incontro diretto con il suo omologo ucraino, nonostante Zelensky avesse inviato una lettera aperta chiedendo di \"fermare la guerra e scegliere la pace\".</p><blockquote>\"Le nostre operazioni di sanzioni a lungo raggio hanno dato buoni risultati. Il terminale petrolifero di Pietroburgo era a 1.100 km dal nostro confine.\" — Volodymyr Zelensky, 6 giugno 2026</blockquote><p>Il ministero della Difesa russo ha comunicato l'abbattimento di 376 droni su 13 regioni diverse, dalla Crimea alla regione di Mosca, dal Mar d'Azov al Mar Nero. I danni effettivi sono difficili da verificare in modo indipendente, ma le immagini del terminal petrolifero di San Pietroburgo in fiamme hanno circolato rapidamente sui media internazionali.</p><h2>Il fronte e i negoziati</h2><p>Sul campo, la situazione rimane di logoramento. A febbraio 2026 l'Ucraina ha lanciato una controffensiva locale sul fronte meridionale nel Dnipropetrovsk, con obiettivi limitati ma significativi. I raid russi continuano a colpire le città: nei giorni scorsi 12 morti nel Donetsk e nel Kherson, 22 vittime in un attacco su Dnipro e Kiev che il governo ucraino ha definito \"uno dei più gravi dall'inizio della guerra\".</p><h2>Il vertice NATO di luglio e i 70 miliardi</h2><p>Sullo sfondo diplomatico, i paesi NATO stanno elaborando un nuovo pacchetto di aiuti finanziari a Kiev da 70 miliardi di euro, da annunciare al vertice di Ankara previsto per il 7 e 8 luglio. Di questi, 40 miliardi sarebbero nuovi stanziamenti e 30 miliardi parte del pacchetto UE già approvato. A complicare la discussione, il rischio del disimpegno americano e il malcontento di alcuni paesi europei sulla distribuzione del peso finanziario. Una frattura che Mosca osserva con attenzione, nella speranza che il fronte occidentale si increi prima che gli aiuti arrivino.</p>"
  },
  {
    "id": 1,
    "title": "La nuova Europa della difesa: riarmo collettivo tra ambizioni e fratture",
    "deck": "Dopo decenni di dipendenza dalla NATO, i paesi europei accelerano sull'autonomia militare. Le divergenze su budget, comando e industria rimangono profonde.",
    "category": "europa",
    "date": "5 giugno 2026",
    "readTime": 5,
    "featured": false,
    "image": "https://images.pexels.com/photos/434673/pexels-photo-434673.jpeg?auto=compress&cs=tinysrgb&w=1260&q=80",
    "body": "<p>L'Europa sta attraversando una trasformazione silenziosa ma radicale nel modo in cui pensa alla propria sicurezza. Dopo anni di retorica sull'autonomia strategica, la pressione geopolitica degli ultimi anni ha trasformato le parole in misure concrete: aumenti record dei budget per la difesa, nuovi framework industriali comuni, e un dibattito sempre più serrato su chi dovrebbe comandare in caso di crisi.</p><h2>Il salto di paradigma</h2><p>Il punto di svolta non è stato un singolo evento, ma l'accumulo di crisi che ha reso evidente quanto fragile fosse il vecchio ordine. La dipendenza energetica dalla Russia, le tensioni commerciali con gli Stati Uniti, la guerra ai confini dell'Unione: tutto ha contribuito a creare un consenso, fragile ma reale.</p><blockquote>\"La sovranità europea non si declama, si finanzia.\" — una formula che circola nei corridoi di Bruxelles.</blockquote><p>I dati parlano chiaro: la maggioranza dei paesi UE ha raggiunto o superato la soglia del 2% del PIL destinato alla difesa richiesta dalla NATO. Germania, Polonia e Paesi Baltici guidano la classifica.</p><h2>Le fratture che restano</h2><p>I numeri nascondono tensioni strutturali che nessun vertice riesce a risolvere. La prima è industriale: ogni paese vuole che i propri soldi finanzino la propria industria. La frammentazione della difesa europea è ancora enorme rispetto a quella americana.</p><p>La seconda tensione è politica: chi comanda? La Francia insiste su una leadership europea autonoma dalla NATO. I paesi dell'Europa orientale preferiscono la garanzia americana dell'Articolo 5. La Germania oscilla tra le due posizioni.</p><h2>Cosa aspettarsi</h2><p>Nei prossimi anni il banco di prova sarà la concretezza: riusciranno i paesi europei a costruire una catena di comando funzionante? Le risposte determineranno se l'autonomia strategica europea rimarrà uno slogan o diventerà realtà.</p>"
  },
  {
    "id": 2,
    "title": "Washington e Città del Messico: commercio, migrazione e la diplomazia della pressione",
    "deck": "L'amministrazione statunitense rilancia le pressioni sul confine sud mentre i negoziati commerciali entrano nella fase più delicata. Tariffe e flussi migratori intrecciano due dossier esplosivi.",
    "category": "americhe",
    "date": "4 giugno 2026",
    "readTime": 4,
    "featured": false,
    "image": "https://images.pexels.com/photos/14071000/pexels-photo-14071000.jpeg?auto=compress&cs=tinysrgb&w=1260&q=80",
    "body": "<p>La relazione tra Stati Uniti e Messico è da sempre uno dei rapporti bilaterali più complessi del continente americano: economicamente simbiotica, politicamente tesa, culturalmente stratificata.</p><h2>Il peso dell'accordo commerciale</h2><p>L'accordo trilaterale che lega Stati Uniti, Messico e Canada è il quadro entro cui si gioca buona parte della partita economica. Il Messico è diventato il principale partner commerciale degli USA grazie anche al nearshoring: la tendenza delle aziende americane a spostare la produzione vicino a casa.</p><blockquote>\"Non accetteremo un accordo che tratti il Messico come un subappaltatore piuttosto che come un partner.\" — posizione espressa da funzionari messicani nei negoziati informali.</blockquote><p>Washington vuole rinegoziare alcune clausole, in particolare quelle sulle regole di origine per il settore automobilistico. Città del Messico risponde: la rinegoziazione è un'opportunità, purché avvenga su basi paritarie.</p><h2>La leva della migrazione</h2><p>Washington usa la minaccia di tariffe e misure punitive per ottenere cooperazione messicana sul controllo dei flussi migratori. Il Messico non vuole assumere il ruolo di \"terzo paese sicuro\" senza contropartite economiche e diplomatiche.</p><h2>Il quadro più ampio</h2><p>Sullo sfondo si muovono forze più grandi: la rivalità sino-americana rende il Messico strategicamente importante come zona di produzione sicura. Capire la relazione USA-Messico significa capire molte delle tensioni che attraversano l'intero continente americano.</p>"
  },
  {
    "id": 3,
    "title": "I Balcani alla svolta: Albania e Montenegro sempre più vicini all'UE",
    "deck": "Il processo di adesione accelera dopo anni di stallo. Bruxelles punta su un allargamento graduale per stabilizzare i Balcani occidentali prima che lo faccia qualcun altro.",
    "category": "europa",
    "date": "3 giugno 2026",
    "readTime": 5,
    "featured": false,
    "image": "https://images.pexels.com/photos/6072869/pexels-photo-6072869.jpeg?auto=compress&cs=tinysrgb&w=1260&q=80",
    "body": "<p>Il cosiddetto \"allargamento\" dell'Unione Europea è stato per anni il grande progetto incompiuto della politica estera di Bruxelles. I Balcani occidentali sono candidati all'adesione da decenni, in un processo che ha visto progressi lentissimi e brusche frenate. Ora qualcosa sembra muoversi davvero.</p><h2>Perché adesso</h2><p>La risposta più onesta è: perché il costo dell'inazione è diventato troppo alto. La presenza di influenza russa e cinese nella regione ha reso evidente a Bruxelles che lasciare i Balcani in un perenne stato di \"quasi-Europa\" non è una strategia sostenibile. È un vuoto che altri riempiono.</p><blockquote>\"L'allargamento non è carità, è interesse strategico. Chi entra nell'UE non entra nell'orbita di Mosca o Pechino.\" — sintesi della nuova retorica europea sull'espansione.</blockquote><p>Montenegro e Albania sono i paesi più avanzati nel processo. Entrambi hanno riformato significativamente le proprie istituzioni, anche se problemi di corruzione e stato di diritto restano una preoccupazione reale per i partner europei.</p><h2>Le resistenze interne</h2><p>All'interno dell'UE, alcuni paesi hanno storicamente frenato sull'allargamento. La questione è anche politica interna: in un'Europa dove i partiti euroscettici sono in ascesa, l'idea di allargare l'Unione non è sempre popolare.</p><h2>Lo scenario nei prossimi anni</h2><p>Se i segnali attuali reggono, Montenegro e Albania potrebbero completare i negoziati di adesione entro il decennio. L'allargamento è tornato nell'agenda prioritaria di Bruxelles come strumento di politica estera in un mondo sempre più competitivo.</p>"
  },
  {
    "id": 4,
    "title": "Brasile e Argentina: un asse impossibile che ridisegna il Mercosur",
    "deck": "Le politiche economiche di Lula e Milei sembrano incompatibili su tutto. Eppure i due paesi si trovano a negoziare un avvicinamento dettato più dalla geopolitica che dall'ideologia.",
    "category": "americhe",
    "date": "2 giugno 2026",
    "readTime": 4,
    "featured": false,
    "image": "https://images.pexels.com/photos/34437872/pexels-photo-34437872.jpeg?auto=compress&cs=tinysrgb&w=1260&q=80",
    "body": "<p>Se dovessimo trovare due leader più distanti sul piano ideologico nell'America Latina contemporanea, sceglieremmo Lula da Silva e Javier Milei. Eppure la relazione Brasile-Argentina è più complessa di un semplice scontro di visioni.</p><h2>La logica della geografia</h2><p>Brasile e Argentina sono i due giganti del Sud America e, insieme, rappresentano circa l'80% del PIL del Mercosur. Questa realtà geografica ed economica crea una dipendenza reciproca che nessun leader può permettersi di ignorare. Gli scambi commerciali tra i due paesi sono enormi; le catene produttive sono profondamente integrate.</p><p>Milei ha criticato Lula apertamente, ma ha anche pragmaticamente mantenuto aperte le linee di comunicazione economica, perché l'alternativa — un Mercosur paralizzato — costa troppo anche all'Argentina in piena crisi strutturale.</p><blockquote>\"In geopolitica, le mappe contano più delle ideologie. Brasile e Argentina sono condannate a intendersi, qualunque cosa pensino i loro presidenti l'uno dell'altro.\"</blockquote><h2>Il Mercosur come banco di prova</h2><p>L'accordo con l'UE — negoziato per decenni e finalmente vicino alla ratifica — è un test: entrambi i paesi lo vogliono, per ragioni diverse. Questo interesse convergente crea uno spazio di cooperazione pratica anche nel mezzo delle tensioni politiche.</p><h2>Una relazione nonostante tutto</h2><p>Brasile e Argentina continueranno a cooperare nonostante le differenze. Non perché i loro leader abbiano trovato un'intesa ideologica, ma perché le strutture economiche, geografiche e geopolitiche che li legano sono più forti di qualsiasi programma politico.</p>"
  },
  {
    "id": 5,
    "title": "Armenia al voto oggi: il Caucaso sospeso tra Russia e Occidente",
    "deck": "Le elezioni parlamentari di Erevan si svolgono questo 7 giugno in un clima di tensione inedita. Pashinyan, sostenuto da UE e USA, affronta le forze filorusse in un voto che decide il futuro geopolitico dell'intera regione.",
    "category": "europa",
    "date": "7 giugno 2026",
    "readTime": 4,
    "featured": false,
    "image": "https://images.pexels.com/photos/17211499/pexels-photo-17211499.jpeg?auto=compress&cs=tinysrgb&w=1260&q=80",
    "body": "<p>Le urne si aprono questa mattina a Erevan e in tutto il paese, e l'Armenia sa bene che quello di oggi non è un appuntamento elettorale ordinario. Le elezioni parlamentari del 7 giugno 2026 sono diventate, nelle ultime settimane, il termometro geopolitico più seguito d'Europa: un piccolo paese del Caucaso meridionale, di meno di tre milioni di abitanti, si trova a rappresentare il nuovo fronte della competizione tra Russia e Occidente.</p><h2>Pashinyan verso il terzo mandato</h2><p>Il premier uscente Nikol Pashinyan, alla guida del paese dal 2018, è in corsa per un terzo mandato consecutivo. Il suo partito, Contratto Civile, è dato in vantaggio dai sondaggi, forte dell'onda di legittimità conquistata con l'avvicinamento all'Unione Europea. A maggio, Erevan ha ospitato l'ottavo vertice della Comunità Politica Europea e un summit diretto UE-Armenia: un palcoscenico costruito con cura per trasmettere all'elettorato l'immagine di un paese che guarda a Ovest con ambizione concreta, non con vaghe aspirazioni.</p><blockquote>\"Non si tratta soltanto di stabilire chi governerà il paese, ma di capire quale direzione prenderà l'Armenia nei prossimi anni.\" — ISPI, analisi pre-elettorale</blockquote><p>Washington ha scelto il campo: l'amministrazione americana ha espresso pubblico sostegno a Pashinyan, in linea con la logica di contenimento dell'influenza russa nel Caucaso post-sovietico. È un segnale di rottura con le ambiguità del passato, e Mosca l'ha percepito come tale.</p><h2>La stretta di Mosca</h2><p>Nelle settimane precedenti il voto, la Russia ha intensificato la pressione su Erevan con ogni strumento disponibile. Al vertice dell'Unione Economica Eurasiatica di Astana, Putin ha lanciato un avvertimento esplicito: un percorso di adesione all'UE rappresenterebbe un rischio per la sicurezza economica dell'intero blocco eurasiatico. Seguono restrizioni commerciali, campagne di disinformazione certificate dall'intelligence armena, e il sostegno indiretto a partiti filorussi che si presentano come alternativa a Pashinyan.</p><p>La pressione non è sottile. L'Armenia dipende ancora in misura significativa dalla Russia per forniture energetiche e per la gestione di una frontiera condivisa con l'Azerbaigian — un paese con cui i rapporti restano tesi nonostante i progressi diplomatici degli ultimi anni.</p><h2>Più di un referendum</h2><p>Gli analisti avvertono di non leggere questo voto come un semplice referendum tra Russia e UE. La realtà armena è più complessa: c'è la questione irrisolta del Nagorno-Karabakh, la difficile normalizzazione con Azerbaigian e Turchia, la fragilità delle istituzioni democratiche. Ridurre tutto a una scelta di campo sarebbe un'analisi rozza. Ma negare la dimensione geopolitica del voto sarebbe cecità. I risultati di questa sera diranno qualcosa di importante non solo sull'Armenia, ma sul perimetro reale dell'influenza russa in Europa orientale.</p>"
  },
  {
    "id": 6,
    "title": "Il Pentagono taglia le brigate in Europa: la NATO affronta il suo nodo irrisolto",
    "deck": "Gli Stati Uniti riducono da quattro a tre le brigate da combattimento nell'Europa e tagliano 5.000 soldati, principalmente dalla Germania. L'Europa risponde con il piano ReArm, ma le domande sulla deterrenza restano aperte.",
    "category": "europa",
    "date": "7 giugno 2026",
    "readTime": 5,
    "featured": false,
    "image": "https://images.pexels.com/photos/17178100/pexels-photo-17178100.jpeg?auto=compress&cs=tinysrgb&w=1260&q=80",
    "body": "<p>Era nell'aria da mesi, ma farlo diventare ufficiale ha comunque il peso di una svolta. Il Pentagono ha confermato la riduzione del contingente americano in Europa da quattro a tre brigate da combattimento, con un taglio netto di circa 5.000 soldati. La Germania — che ospita la componente più numerosa con circa 39.000 militari — assorbirà la parte maggiore dei tagli. Polonia e Italia seguono a distanza. Il messaggio politico è chiaro: l'America sta ridisegnando la propria presenza nell'alleanza, e l'Europa deve attrezzarsi di conseguenza.</p><h2>Il piano ReArm Europe risponde</h2><p>L'Europa non è stata colta di sorpresa. Il piano ReArm Europe, approvato a inizio 2025 e ora nella sua fase operativa, ha già attivato la clausola di salvaguardia nazionale in 17 paesi UE, consentendo uno sforamento controllato dei parametri di bilancio per finanziare la difesa fino all'1,5% del PIL aggiuntivo per quattro anni. Il pacchetto SAFE — 150 miliardi di euro per appalti congiunti in sicurezza e difesa — è entrato in vigore a maggio 2025. I numeri ci sono. Ma i numeri non bastano.</p><blockquote>\"Spendere di più non è però più sufficiente. Gli Stati membri devono spendere meglio, collaborare e dare priorità alle imprese europee.\" — Commissione europea, piano ReArm Europe</blockquote><p>La questione non è tanto finanziaria quanto strutturale. L'industria della difesa europea è ancora frammentata in decine di sistemi d'arma nazionali incompatibili, con standard tecnici divergenti e filiere produttive che si sovrappongono anziché integrarsi. Costruire una deterrenza credibile richiede anni di standardizzazione che nessun vertice può accelerare per decreto.</p><h2>La geometria della nuova NATO</h2><p>La riduzione americana apre interrogativi profondi sulla geometria dell'alleanza. I paesi dell'Europa orientale — Polonia, Paesi Baltici, Romania — che si sentono più direttamente esposti alla minaccia russa, guardano con preoccupazione alla diminuzione del presidio americano. La loro logica è semplice: le capacità europee in costruzione non compensano, nel breve periodo, il ritiro di un deterrente operativo già presente.</p><p>La Francia, al contrario, legge il ritiro americano come un'opportunità storica per accelerare sull'autonomia strategica europea. La Germania, come sempre, si muove con cautela. Il risultato è una NATO più ricca di risorse proprie ma più divisa sulle priorità. Una tensione che il segretario Rubio ha cercato di gestire al vertice di Helsingborg, senza però scioglierla.</p><h2>Il nodo della credibilità</h2><p>La credibilità di una deterrenza dipende dalla percezione del potenziale avversario. La Russia misura con attenzione i segnali che arrivano dall'Occidente. Il taglio delle brigate americane, letto insieme alla lentezza dell'integrazione industriale europea, potrebbe essere interpretato come un indebolimento della risposta collettiva. Non è detto che lo sia. Ma la percezione conta quanto la realtà, in geopolitica.</p>"
  },
  {
    "id": 7,
    "title": "Venezuela cinque mesi dopo: la dottrina Monroe di Trump e il continente spaccato",
    "deck": "A gennaio 2026 gli Stati Uniti intervennero militarmente in Venezuela, catturando Maduro. Cinque mesi dopo il paese è in transizione caotica e l'America Latina resta profondamente divisa su cosa sia davvero accaduto.",
    "category": "americhe",
    "date": "7 giugno 2026",
    "readTime": 5,
    "featured": false,
    "image": "https://images.pexels.com/photos/13966906/pexels-photo-13966906.jpeg?auto=compress&cs=tinysrgb&w=1260&q=80",
    "body": "<p>Quando a gennaio 2026 gli Stati Uniti lanciarono operazioni militari in Venezuela portando alla cattura di Nicolás Maduro, molti osservatori lessero l'evento come l'epilogo di una crisi decennale. Cinque mesi dopo, quella lettura appare semplicistica. Il Venezuela è in una fase di transizione caotica, le risorse petrolifere del paese sono sotto controllo americano, e il continente latinoamericano è attraversato da fratture profonde sulla legittimità di quanto accaduto.</p><h2>La formula Trump</h2><p>Donald Trump ha definito l'intervento in Venezuela come un modello applicabile ad altri contesti: la cosiddetta \"formula Venezuela\", una combinazione di pressione economica prolungata, operazioni di intelligence, e azione militare mirata finalizzata alla rimozione di leadership considerate ostili agli interessi americani. Dopo la gestione della crisi iraniana — conclusa secondo la Casa Bianca con un accordo favorevole agli USA — il Venezuela è stato presentato come la conferma che la dottrina funziona.</p><blockquote>\"Ha preso il controllo delle risorse petrolifere del Venezuela\" e si prepara ad \"applicare la formula Venezuela\" ad altri regimi ostili. — Fonti vicine all'amministrazione americana</blockquote><p>La NATO nella sua componente europea ha sostanzialmente appoggiato l'intervento, almeno nella comunicazione ufficiale. Diversa la reazione della maggior parte dei paesi africani, asiatici e latinoamericani, che hanno condannato le operazioni come violazione del diritto internazionale e del principio di non intervento. Colombia, che condivide un lungo confine con il Venezuela, ha mobilizzato le forze di sicurezza lungo il confine sin dai primi giorni del gennaio 2026.</p><h2>Il dopo-Maduro</h2><p>La transizione venezuelana è tutt'altro che lineare. Le strutture dello Stato chavista, costruite in venticinque anni, non si smontano con un'operazione militare. Le fazioni interne al vecchio regime si sono riorganizzate, i flussi migratori verso Colombia e Brasile non si sono arrestati, e la ricostruzione economica dipende da investimenti che per ora stentano ad arrivare. Il controllo americano delle risorse petrolifere è contestato internazionalmente e presenta complicazioni giuridiche significative.</p><h2>Un continente che si interroga</h2><p>L'intervento americano in Venezuela ha riaperto nel continente un dibattito che si credeva superato: quello sui limiti della sovranità, sul diritto di ingerenza e sulla legittimità dell'unilateralismo americano nell'emisfero. Brasile e Argentina — con governi ideologicamente distanti — hanno risposto in modo diverso ma entrambi con diffidenza. Il Mercosur ne esce indebolito come forum di coordinamento politico. E la domanda che attraversa molte capitali latinoamericane è la stessa: chi sarà il prossimo?</p>"
  },
  {
    "id": 8,
    "title": "Cuba e il grande riposizionamento: l'isola al centro del calcolo strategico americano",
    "deck": "Mentre il continente americano si riassesta dopo gli shock del 2026, Cuba emerge come un nodo inatteso della strategia di Washington nell'emisfero. Un doppio calcolo che potrebbe cambiare decenni di politica estera.",
    "category": "americhe",
    "date": "7 giugno 2026",
    "readTime": 4,
    "featured": false,
    "image": "https://images.pexels.com/photos/11733822/pexels-photo-11733822.jpeg?auto=compress&cs=tinysrgb&w=1260&q=80",
    "body": "<p>Sessanta anni di embargo, isolamento diplomatico e guerre fredde mai del tutto concluse. Eppure, nell'estate del 2026, Cuba è tornata al centro della riflessione strategica americana con un'urgenza che sorprende. Non perché il regime dell'Avana abbia cambiato natura, ma perché la geopolitica dell'emisfero si è trasformata a una velocità tale da rimettere in discussione certezze che sembravano consolidate.</p><h2>Il doppio calcolo di Washington</h2><p>L'interesse americano per Cuba si muove su due assi paralleli e in parte contraddittori. Il primo è di natura militare e strategica: l'isola, posizionata a novanta miglia dalla Florida, rappresenta un punto di proiezione che nessun pianificatore del Pentagono può permettersi di ignorare, soprattutto in un contesto in cui la Cina ha intensificato la propria presenza nell'America Latina e nei Caraibi. La presenza di infrastrutture di intelligence cinesi a Cuba è documentata e considerata una minaccia diretta.</p><blockquote>\"Cuba appare oggi al centro di un possibile duplice calcolo strategico per gli Stati Uniti.\" — Notizie Geopolitiche, giugno 2026</blockquote><p>Il secondo asse è economico: il Venezuela post-intervento ha riorganizzato i flussi petroliferi della regione, e Cuba — che dipendeva storicamente dal petrolio venezuelano a condizioni agevolate — si trova in una posizione di fragilità acuta. Una fragilità che Washington potrebbe scegliere di sfruttare come leva di pressione, oppure come apertura negoziale.</p><h2>L'opzione del dialogo</h2><p>Alcuni funzionari dell'amministrazione Trump, in dichiarazioni riservate riportate da media americani, hanno lasciato intendere che un riorientamento della politica cubana non è escluso dal tavolo. L'idea non è una normalizzazione ideologica — l'approccio all'Avana resterebbe duro — ma una transazione pragmatica: aperture economiche selettive in cambio di concessioni sulla presenza cinese e sull'utilizzo dell'isola come piattaforma di attività ostili agli USA.</p><p>È uno schema già visto: Trump applica alla geopolitica la logica del deal, indipendentemente dalle tradizioni diplomatiche o dalle sensibilità ideologiche. Il risultato può essere sorprendente, nel bene o nel male. L'Europa osserva con attenzione, consapevole che una normalizzazione rapida USA-Cuba cambierebbe gli equilibri dell'intera regione caraibica — e i propri interessi commerciali nell'isola.</p><h2>Un'isola che aspetta</h2><p>Sull'altro lato dell'equazione c'è Cuba stessa, un paese che attraversa una delle crisi economiche più gravi della sua storia post-rivoluzionaria. La popolazione è esaurita, l'emigrazione non si ferma, le strutture dello stato mostrano segni di logoramento. In questo contesto, l'eventualità di un riavvicinamento con gli USA — anche parziale, anche strumentale — non può essere esclusa a priori. La storia insegna che i regimi apparentemente immobili cambiano quando i costi del non cambiamento diventano insostenibili.</p>"
  }
]